<?php
  $access_token = FreshRSS_Context::$user_conf->raindrop_access_token;
  $client_id = FreshRSS_Context::$user_conf->client_id;
  $client_secret = FreshRSS_Context::$user_conf->client_secret;
  $keyboard_shortcut = FreshRSS_Context::$user_conf->keyboard_shortcut;
  $redirect_uri = FreshRSS_Context::$user_conf->redirect_uri
?>

<form action="<?php echo _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post">
	<input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />
	<div class="form-group">
		<label class="group-name" for="keyboard_shortcut"><?php echo _t('ext.starToRaindropIO.configure.keyboard_shortcut'); ?></label>
		<div class="group-controls">
			<input type="text" name="keyboard_shortcut" id="keyboard_shortcut" maxlength="1" value="<?php echo $keyboard_shortcut; ?>">
		</div>
	</div>

	<div class="form-group form-actions">
		<div class="group-controls">
			<button type="submit" class="btn btn-important"><?php echo _t('gen.action.submit'); ?></button>
		</div>
	</div>
</form>

<?php if ($this->isEnabled() && empty($access_token)): ?>
<form action="<?php echo _url('starToRaindropIO', 'requestAccess'); ?>" method="post">
	<input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />
	<div class="form-group">
		<label class="group-name" for="client_id"><?php echo _t('ext.starToRaindropIO.configure.client_id'); ?></label>
		<div class="group-controls">
      <input type="text" name="client_id" id="client_id" value="<?php echo $client_id; ?>">
      <input type="text" name="client_secret" id="client_secret" value="<?php echo $client_secret; ?>">
      <input type="text" name="redirect_uri" id="redirect_uri" value="<?php echo $redirect_uri; ?>">
		</div>
	</div>

	<div class="alert alert-warn">
		<?php echo _t('ext.starToRaindropIO.configure.client_id_description'); ?>
	</div>
	
	<div class="form-group form-actions">
		<div class="group-controls">
			<button type="submit" class="btn btn-important"><?php echo _t('ext.starToRaindropIO.configure.connect_to_raindrop'); ?></button>
		</div>
	</div>
</form>
<?php elseif (!$this->isEnabled()): ?>
	<p class="alert alert-error">
		<?php echo _t('ext.starToRaindropIO.configure.extension_disabled'); ?>
	</p>
<?php endif ?>

<?php if (!empty($access_token)): ?>
	<p class="alert alert-success">
		<?php echo _t('ext.starToRaindropIO.configure.connected_to_raindrop', $access_token); ?>
	</p>
	<form action="<?php echo _url('starToRaindropIO', 'revokeAccess'); ?>" method="post">
		<input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />
		<div class="form-group form-actions">
			<div class="group-controls">
				<button type="submit" class="btn btn-important"><?php echo _t('ext.starToRaindropIO.configure.revoke_access'); ?></button>
			</div>
		</div>
	</form>
<?php endif ?>
